// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASOdowvmHOZDzom6tOzlBJc-CpvCizDHg',
    appId: '1:992887829613:web:6e5e01495d69e0c65f3b64',
    messagingSenderId: '992887829613',
    projectId: 'mynite-e41e2',
    authDomain: 'mynite-e41e2.firebaseapp.com',
    storageBucket: 'mynite-e41e2.appspot.com',
    measurementId: 'G-5PEJXHL0GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSR9qP7BNr4X0j7Fv2hzvUfaT8kM5c_G8',
    appId: '1:992887829613:android:7eb7718d46e86b355f3b64',
    messagingSenderId: '992887829613',
    projectId: 'mynite-e41e2',
    storageBucket: 'mynite-e41e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLI0NEBEzE7whIW6ah8dPFOe_JM5kJIlA',
    appId: '1:992887829613:ios:6f6a72004d597cea5f3b64',
    messagingSenderId: '992887829613',
    projectId: 'mynite-e41e2',
    storageBucket: 'mynite-e41e2.appspot.com',
    iosClientId: '992887829613-9e07slc4cncllqsv2nede59f7s85392s.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLI0NEBEzE7whIW6ah8dPFOe_JM5kJIlA',
    appId: '1:992887829613:ios:f103a5e264b11deb5f3b64',
    messagingSenderId: '992887829613',
    projectId: 'mynite-e41e2',
    storageBucket: 'mynite-e41e2.appspot.com',
    iosClientId: '992887829613-4d26m61gq37r7r7spgicbk7fef8mnto9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes.RunnerTests',
  );
}
